# Generated by Django 4.2.5 on 2023-10-14 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prisme_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='nome',
            new_name='nome_projeto',
        ),
    ]
