# Generated by Django 4.2.5 on 2023-10-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prisme_app', '0004_remove_ong_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ong',
            name='email',
            field=models.EmailField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
