# Generated by Django 4.2.5 on 2023-10-14 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prisme_app', '0008_remove_dadosimpactos_tipo_dadosimpactos_tipo1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadosimpactos',
            name='valor1',
        ),
        migrations.RemoveField(
            model_name='dadosimpactos',
            name='valor2',
        ),
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor2', models.CharField(max_length=20)),
                ('dado_impacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prisme_app.dadosimpactos')),
            ],
        ),
    ]
