# Generated by Django 4.2.5 on 2023-10-14 18:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("prisme_app", "0009_remove_dadosimpactos_valor1_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Dados",
            new_name="LinhasImpacto",
        ),
    ]
