# Generated by Django 4.2.5 on 2023-10-14 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prisme_app', '0010_alter_ong_areaatuação'),
        ('prisme_app', '0010_rename_dados_linhasimpacto'),
    ]

    operations = [
    ]
