# Generated by Django 4.2.5 on 2023-10-14 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prisme_app', '0011_merge_20231014_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ong',
            name='areaAtuação',
            field=models.CharField(choices=[(None, 'Selecione a área de atuação'), ('Esportes', 'Esportes'), ('Direitos Humanos', 'Direitos Humanos'), ('Educação', 'Educação'), ('Saúde', 'Saúde'), ('Cultura e Arte', 'Cultura e Arte'), ('Meio Ambiente', 'Meio Ambiente'), ('Desenvolvimento Comunitário', 'Desenvolvimento Comunitário'), ('Ajuda Humanitária', 'Ajuda Humanitária'), ('Empreendedorismo Social', 'Empreendedorismo Social'), ('Alívio da Pobreza', 'Alívio da Pobreza'), ('Alimentação e segurança alimentar', 'Alimentação e segurança alimentar'), ('Causa animal', 'Causa animal'), ('Desenvolvimento internacional', 'Desenvolvimento internacional'), ('Outro', 'Outro')], default=(None, 'Selecione a área de atuação'), max_length=50),
        ),
    ]
