# Generated by Django 4.2.6 on 2023-10-15 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prisme_app', '0011_alter_ong_areaatuação'),
        ('prisme_app', '0012_alter_ong_areaatuação'),
    ]

    operations = [
    ]
