# Generated by Django 4.2.5 on 2023-10-16 00:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("prisme_app", "0013_merge_20231015_1013"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ong",
            old_name="areaAtuação",
            new_name="areaAtuacao",
        ),
    ]
