# Generated by Django 4.2.5 on 2023-11-06 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("prisme_app", "0014_rename_areaatuação_ong_areaatuacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("Ganho", "Ganho"), ("Gasto", "Gasto")],
                        default=("Gasto", "Gasto"),
                        max_length=100,
                    ),
                ),
                (
                    "ong",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="prisme_app.ong"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LinhaCaixa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.IntegerField()),
                ("data", models.DateField()),
                ("identificacao", models.CharField(max_length=100)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prisme_app.categoria",
                    ),
                ),
            ],
        ),
    ]
