# Generated by Django 4.2.5 on 2023-11-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prisme_app', '0015_categoria_linhacaixa'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditarEstilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sidebar', models.CharField(max_length=20)),
                ('background', models.CharField(max_length=20)),
            ],
        ),
    ]
