# Generated by Django 4.2.5 on 2023-11-13 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prisme_app', '0016_editarestilo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editarestilo',
            old_name='background',
            new_name='backcor',
        ),
    ]
