# Generated by Django 4.2.5 on 2023-11-13 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prisme_app', '0017_rename_background_editarestilo_backcor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editarestilo',
            old_name='sidebar',
            new_name='sidecor',
        ),
    ]
