# Generated by Django 4.2.5 on 2023-11-13 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prisme_app', '0018_rename_sidebar_editarestilo_sidecor'),
    ]

    operations = [
        migrations.AddField(
            model_name='editarestilo',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
