# Generated by Django 4.2.5 on 2023-11-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prisme_app', '0019_editarestilo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editarestilo',
            name='backcor',
            field=models.CharField(default='#f5f7fa', max_length=20),
        ),
        migrations.AlterField(
            model_name='editarestilo',
            name='sidecor',
            field=models.CharField(default='#fff', max_length=20),
        ),
    ]
