# Generated by Django 4.2.5 on 2023-11-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prisme_app', '0020_alter_editarestilo_backcor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editarestilo',
            name='sidecor',
            field=models.CharField(default='#FFFFFF', max_length=20),
        ),
    ]
