# Generated by Django 4.2.5 on 2023-11-21 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prisme_app', '0022_voluntariado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntariado',
            name='genero',
            field=models.CharField(choices=[(None, 'Selecione...'), ('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Outro', 'Outro')], default=(None, 'Selecione...'), max_length=50),
        ),
    ]
