# Generated by Django 4.2.5 on 2023-11-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prisme_app", "0023_alter_voluntariado_genero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dadosimpactos",
            name="tipo1",
            field=models.CharField(
                choices=[
                    (None, "Selecione o tipo de dado"),
                    ("Pessoas Impactadas", "Pessoas Impactadas"),
                    ("Casas Contruidas", "Casas Contruidas"),
                    ("Árvores plantadas", "Árvores plantadas"),
                    ("Lixo removido (TON)", "Lixo removido (TON)"),
                    ("Médicos alocados", "Médicos alocados"),
                    ("Alunos ajudados", "Alunos ajudados"),
                    ("Merendas Disponibilizadas", "Merendas Disponibilizadas"),
                    ("Tratamentos Disponibilizadas", "Tratamentos Disponibilizadas"),
                    ("Animais ajudados", "Animais ajudados"),
                ],
                default=(None, "Selecione o tipo de dado"),
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="dadosimpactos",
            name="tipo2",
            field=models.CharField(
                choices=[
                    (None, "Selecione o tipo de dado"),
                    ("Tempo", "Tempo"),
                    ("Pessoa", "Pessoa"),
                    ("Km2", "Km2"),
                    ("Bairro", "Bairro"),
                    ("Estado", "Estado"),
                ],
                default=(None, "Selecione o tipo de dado"),
                max_length=50,
            ),
        ),
    ]
