# Generated by Django 4.2.5 on 2023-11-25 01:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prisme_app", "0024_alter_dadosimpactos_tipo1_alter_dadosimpactos_tipo2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voluntariado",
            name="horas",
            field=models.CharField(max_length=50),
        ),
    ]
